// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "../libraries/SignatureValidation.sol";

/**
 * @dev Candidate-only issuer signal. It is intentionally not a production ABI.
 */
interface IPhase2ALaunchTokenIssuerCandidate {
    function cipherDEXLaunchIssuer() external view returns (address);
}

contract MockPhase2ALaunchIssuerToken is IPhase2ALaunchTokenIssuerCandidate {
    address public immutable issuer;

    constructor(address issuer_) {
        require(issuer_ != address(0), "issuer");
        issuer = issuer_;
    }

    function cipherDEXLaunchIssuer() external view returns (address) {
        return issuer;
    }
}

/**
 * @notice Disposable authorization probe. The issuer signs only static launch
 *         authority. executionValuesTag models future transaction-scoped GT and
 *         is deliberately excluded from the signed digest.
 */
contract ProtectedVaultAuthorizationProbe {
    bytes32 public constant EIP712_DOMAIN_TYPEHASH = keccak256(
        "EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"
    );
    bytes32 public constant AUTHORIZATION_TYPEHASH = keccak256(
        "VaultAuthorization(address factory,uint256 protocolVersion,uint8 privacyMode,uint8 poolKind,address token0,address token1,uint256 feeBps,address protectedToken,address issuer,address vault,uint8 disposition,uint256 nonce,uint64 deadline)"
    );
    bytes32 private constant NAME_HASH = keccak256(
        "CipherDEX Phase2A Vault Authorization Probe"
    );
    bytes32 private constant VERSION_HASH = keccak256("1");
    uint8 public constant PROTECTED_POOL_KIND = 1;

    struct StaticTerms {
        address tokenA;
        address tokenB;
        uint256 feeBps;
        address protectedToken;
        uint8 disposition;
    }

    address public immutable factory;
    uint256 public immutable protocolVersion;
    uint8 public immutable privacyMode;
    uint256 public immutable deploymentChainId;
    bytes32 private immutable deploymentDomainSeparator;
    mapping(address => uint256) public nextNonce;
    uint256 public executionCount;

    error InvalidConfiguration();
    error InvalidStaticTerms();
    error VaultOnly();
    error AuthorizationExpired();
    error InvalidNonce();
    error InvalidIssuerAuthorization();
    error ExecutionFailed();

    event StaticAuthorizationConsumed(
        address indexed issuer,
        address indexed vault,
        address indexed protectedToken,
        uint256 nonce
    );

    constructor(address factory_, uint256 protocolVersion_, uint8 privacyMode_) {
        if (factory_ == address(0) || protocolVersion_ == 0) {
            revert InvalidConfiguration();
        }
        factory = factory_;
        protocolVersion = protocolVersion_;
        privacyMode = privacyMode_;
        deploymentChainId = block.chainid;
        deploymentDomainSeparator = _buildDomainSeparator(block.chainid);
    }

    function authorizationDigest(
        StaticTerms calldata terms,
        address vault,
        uint256 nonce,
        uint64 deadline
    ) external view returns (bytes32) {
        (address token0, address token1, address issuer) = _validatedTerms(terms);
        return _hashTypedData(
            _authorizationStructHash(
                terms,
                token0,
                token1,
                issuer,
                vault,
                nonce,
                deadline
            )
        );
    }

    function authorizeVaultExecution(
        StaticTerms calldata terms,
        address vault,
        uint256 nonce,
        uint64 deadline,
        bytes calldata issuerSignature,
        bytes32 executionValuesTag,
        bool failAfterConsumption
    ) external returns (bytes32 staticAuthorizationDigest) {
        if (msg.sender != vault || vault == address(0)) revert VaultOnly();
        if (deadline < block.timestamp) revert AuthorizationExpired();

        (address token0, address token1, address issuer) = _validatedTerms(terms);
        if (nonce != nextNonce[issuer]) revert InvalidNonce();
        staticAuthorizationDigest = _hashTypedData(
            _authorizationStructHash(
                terms,
                token0,
                token1,
                issuer,
                vault,
                nonce,
                deadline
            )
        );
        if (
            !SignatureValidation.isValidSignatureNow(
                issuer,
                staticAuthorizationDigest,
                issuerSignature
            )
        ) revert InvalidIssuerAuthorization();

        nextNonce[issuer] = nonce + 1;
        executionCount += 1;

        // The tag stands in for values generated by the authorized vault during
        // execution. It is checked for presence but is intentionally not signed.
        if (executionValuesTag == bytes32(0) || failAfterConsumption) {
            revert ExecutionFailed();
        }

        emit StaticAuthorizationConsumed(
            issuer,
            vault,
            terms.protectedToken,
            nonce
        );
    }

    function domainSeparator() public view returns (bytes32) {
        return block.chainid == deploymentChainId
            ? deploymentDomainSeparator
            : _buildDomainSeparator(block.chainid);
    }

    function _validatedTerms(
        StaticTerms calldata terms
    ) internal view returns (address token0, address token1, address issuer) {
        if (
            terms.tokenA == address(0) ||
            terms.tokenB == address(0) ||
            terms.tokenA == terms.tokenB ||
            terms.protectedToken == address(0) ||
            (
                terms.protectedToken != terms.tokenA &&
                terms.protectedToken != terms.tokenB
            )
        ) revert InvalidStaticTerms();
        (token0, token1) = terms.tokenA < terms.tokenB
            ? (terms.tokenA, terms.tokenB)
            : (terms.tokenB, terms.tokenA);
        try IPhase2ALaunchTokenIssuerCandidate(terms.protectedToken)
            .cipherDEXLaunchIssuer() returns (address candidateIssuer)
        {
            issuer = candidateIssuer;
        } catch {
            revert InvalidStaticTerms();
        }
        if (issuer == address(0)) revert InvalidStaticTerms();
    }

    function _authorizationStructHash(
        StaticTerms calldata terms,
        address token0,
        address token1,
        address issuer,
        address vault,
        uint256 nonce,
        uint64 deadline
    ) internal view returns (bytes32) {
        return keccak256(
            abi.encode(
                AUTHORIZATION_TYPEHASH,
                factory,
                protocolVersion,
                privacyMode,
                PROTECTED_POOL_KIND,
                token0,
                token1,
                terms.feeBps,
                terms.protectedToken,
                issuer,
                vault,
                terms.disposition,
                nonce,
                deadline
            )
        );
    }

    function _hashTypedData(bytes32 structHash) internal view returns (bytes32) {
        return keccak256(abi.encodePacked("\x19\x01", domainSeparator(), structHash));
    }

    function _buildDomainSeparator(uint256 chainId) internal view returns (bytes32) {
        return keccak256(
            abi.encode(
                EIP712_DOMAIN_TYPEHASH,
                NAME_HASH,
                VERSION_HASH,
                chainId,
                address(this)
            )
        );
    }
}
