export const CT_UINT256 = "(uint256 ciphertextHigh,uint256 ciphertextLow)";
export const IT_UINT256 = `(${CT_UINT256} ciphertext,bytes signature)`;

export const PRIVATE_ERC20_TESTNET_ABI = [
  "function decimals() view returns (uint8)",
  "function publicAmountsEnabled() view returns (bool)",
  "function accountEncryptionAddress(address account) view returns (address)",
  `function balanceOf(address account) view returns (${CT_UINT256} balance)`,
  `function allowance(address owner,address spender) view returns ((${CT_UINT256} ciphertext,${CT_UINT256} ownerCiphertext,${CT_UINT256} spenderCiphertext) value)`,
  `function approve(address spender,${IT_UINT256} amount)`,
] as const;

export const CONFIDENTIAL_POOL_TESTNET_ABI = [
  "error InvalidPrivateAmount()",
  "error PoolNotInitialized()",
  "error PoolAlreadyInitialized()",
  "error ArithmeticOverflow()",
  "error ArithmeticUnderflow()",
  "error DivisionByZero()",
  "error SlippageExceeded()",
  "error InsufficientPrivateLiquidity()",
  "error InsufficientPrivateShares()",
  "error InvalidLiquidityRatio()",
  "error InputAlreadyConsumed()",
  "error DeadlineExpired()",
  "error Reentrancy()",
  "function token0() view returns (address)",
  "function token1() view returns (address)",
  "function feeBps() view returns (uint256)",
  "function feeVault() view returns (address)",
  "function PROTOCOL_FEE_SHARE_NUMERATOR() view returns (uint256)",
  "function PROTOCOL_FEE_SHARE_DENOMINATOR() view returns (uint256)",
  "function protocolFeeSwapCount0() view returns (uint32)",
  "function protocolFeeSwapCount1() view returns (uint32)",
  "function protocolFeeWindowStart0() view returns (uint64)",
  "function protocolFeeWindowStart1() view returns (uint64)",
  "function lpToken() view returns (address)",
  "function initialized() view returns (bool)",
  `function myShares() returns (${CT_UINT256} shares)`,
  `function quoteExactInput(${IT_UINT256} amountIn,bool zeroForOne) returns (${CT_UINT256} amountOut)`,
  `function requestQuoteExactInput(${IT_UINT256} amountIn,bool zeroForOne,bytes32 requestId) returns (${CT_UINT256} result)`,
  `function swapExactInput(${IT_UINT256} amountIn,${IT_UINT256} minAmountOut,bool zeroForOne,uint64 deadline) returns (${CT_UINT256} amountOut)`,
  `function addLiquidity(${IT_UINT256} amount0Desired,${IT_UINT256} amount1Desired,${IT_UINT256} minShares,uint64 deadline) returns (${CT_UINT256} mintedShares)`,
  `function removeLiquidity(${IT_UINT256} shares,${IT_UINT256} minAmount0,${IT_UINT256} minAmount1,uint64 deadline) returns (${CT_UINT256} amount0,${CT_UINT256} amount1)`,
  `function lockShares(${IT_UINT256} shares,uint64 unlockTime,bool permanent,uint64 deadline) returns (bytes32 lockId)`,
  "function unlockShares(bytes32 lockId)",
  "function collectProtocolFees(bool collectToken0,bool collectToken1)",
  "function lockInfo(bytes32 lockId) view returns (address owner,uint64 unlockTime,bool permanent,bool released)",
  "event LiquidityLocked(bytes32 indexed lockId,address indexed owner,uint64 unlockTime,bool permanent)",
  `event ConfidentialQuoteResult(address indexed caller,bytes32 indexed requestId,bool indexed zeroForOne,${CT_UINT256} result)`,
  "event ConfidentialProtocolFeesCollected(address indexed token,address indexed feeVault,uint32 aggregatedSwapCount)",
] as const;
