export const CT_UINT256 = "(uint256 ciphertextHigh,uint256 ciphertextLow)";
export const IT_UINT256 = `(${CT_UINT256} ciphertext,bytes signature)`;

export const PRIVATE_ERC20_TESTNET_ABI = [
  "function decimals() view returns (uint8)",
  "function publicAmountsEnabled() view returns (bool)",
  "function accountEncryptionAddress(address account) view returns (address)",
  `function balanceOf(address account) view returns (${CT_UINT256} balance)`,
  `function allowance(address owner,address spender) view returns ((${CT_UINT256} ciphertext,${CT_UINT256} ownerCiphertext,${CT_UINT256} spenderCiphertext) value)`,
  `function approve(address spender,${IT_UINT256} amount)`,
  `function transfer(address to,${IT_UINT256} amount)`,
] as const;

export const CONFIDENTIAL_FACTORY_TESTNET_ABI = [
  "function PROTOCOL_VERSION() view returns (uint256)",
  "function PRIVACY_MODE() view returns (uint8)",
  "function feeVault() view returns (address)",
  "function poolDeployer() view returns (address)",
  "function initializationStrategyRegistry() view returns (address)",
  "function isCompatiblePrivateToken(address token) view returns (bool)",
  "function isPool(address pool) view returns (bool)",
  "function bestExecutionRouter() view returns (address)",
  "function BEST_EXECUTION_ROUTER_RUNTIME_CODEHASH() view returns (bytes32)",
  "function getPool(bytes32 key) view returns (address)",
  "function poolKey(address token0,address token1,uint8 decimals0,uint8 decimals1,uint256 feeBps,address initializationStrategy) pure returns (bytes32)",
  "function createPool(address tokenA,address tokenB,uint8 decimalsA,uint8 decimalsB,uint256 feeBps) returns (address)",
  "function setBestExecutionRouter(address router)",
] as const;

export const CONFIDENTIAL_BEST_EXECUTION_ROUTER_TESTNET_ABI = [
  "error InvalidTokenPair()",
  "error UnsupportedPrivateToken()",
  "error InvalidCanonicalPool()",
  "error NoViablePool()",
  "error InvalidRequestId()",
  "error RequestAlreadyUsed()",
  "error InputAlreadyConsumed()",
  "error DeadlineExpired()",
  "error PrivateTransferAmountMismatch()",
  "error QuoteSettlementMismatch()",
  "error ResidualAllowance()",
  "function PROTOCOL_VERSION() view returns (uint256)",
  "function factory() view returns (address)",
  "function MAX_CANDIDATES() view returns (uint8)",
  "function MAX_QUOTE_CANDIDATES() view returns (uint8)",
  "function usedRequestIds(address caller,bytes4 selector,bytes32 requestId) view returns (bool)",
  `function requestBestQuoteExactInput(address tokenIn,address tokenOut,${IT_UINT256} amountIn,bytes32 requestId,uint64 deadline) returns (${CT_UINT256} result)`,
  `function requestBestQuoteExactInputWithCandidates(address tokenIn,address tokenOut,${IT_UINT256} amountIn,uint16 candidateBitmap,bytes32 requestId,uint64 deadline) returns (${CT_UINT256} result)`,
  `function swapBestExactInput(address tokenIn,address tokenOut,${IT_UINT256} amountIn,${IT_UINT256} minimumOut,bytes32 requestId,uint64 deadline) returns (${CT_UINT256} result)`,
  `function swapBestExactInputWithCandidates(address tokenIn,address tokenOut,${IT_UINT256} amountIn,${IT_UINT256} minimumOut,uint16 candidateBitmap,bytes32 requestId,uint64 deadline) returns (${CT_UINT256} result)`,
  `event ConfidentialBestQuoteResult(address indexed caller,bytes32 indexed requestId,address indexed selectedPool,uint256 selectedFeeBps,address selectedInitializationStrategy,uint16 candidateBitmap,bool zeroForOne,${CT_UINT256} result)`,
  `event ConfidentialBestSwapResult(address indexed caller,bytes32 indexed requestId,address indexed selectedPool,uint256 selectedFeeBps,address selectedInitializationStrategy,uint16 candidateBitmap,bool zeroForOne,${CT_UINT256} result)`,
] as const;

export const CONFIDENTIAL_POOL_TESTNET_ABI = [
  "error InvalidPrivateAmount()",
  "error PoolNotInitialized()",
  "error PoolAlreadyInitialized()",
  "error ArithmeticOverflow()",
  "error ArithmeticUnderflow()",
  "error DivisionByZero()",
  "error SlippageExceeded()",
  "error InsufficientPrivateLiquidity()",
  "error InsufficientPrivateShares()",
  "error InvalidLiquidityRatio()",
  "error InputAlreadyConsumed()",
  "error DeadlineExpired()",
  "error Reentrancy()",
  "function PROTOCOL_VERSION() view returns (uint256)",
  "function PRIVACY_MODE() view returns (uint8)",
  "function token0() view returns (address)",
  "function token1() view returns (address)",
  "function token0Decimals() view returns (uint8)",
  "function token1Decimals() view returns (uint8)",
  "function scale0() view returns (uint256)",
  "function scale1() view returns (uint256)",
  "function feeBps() view returns (uint256)",
  "function feeVault() view returns (address)",
  "function bootstrapper() view returns (address)",
  "function initializationStrategy() view returns (address)",
  "function PROTOCOL_FEE_SHARE_NUMERATOR() view returns (uint256)",
  "function PROTOCOL_FEE_SHARE_DENOMINATOR() view returns (uint256)",
  "function protocolFeeSwapCount0() view returns (uint32)",
  "function protocolFeeSwapCount1() view returns (uint32)",
  "function protocolFeeWindowStart0() view returns (uint64)",
  "function protocolFeeWindowStart1() view returns (uint64)",
  "function nextLockNonce() view returns (uint256)",
  "function lpToken() view returns (address)",
  "function initialized() view returns (bool)",
  "function protectedInitializationCompleted() view returns (bool)",
  `function myShares() returns (${CT_UINT256} shares)`,
  `function quoteExactInput(${IT_UINT256} amountIn,bool zeroForOne) returns (${CT_UINT256} amountOut)`,
  `function requestQuoteExactInput(${IT_UINT256} amountIn,bool zeroForOne,bytes32 requestId) returns (${CT_UINT256} result)`,
  `function requestAddLiquidityQuote(${IT_UINT256} specifiedAmount,bool token0Specified,bytes32 requestId,uint64 deadline) returns (${CT_UINT256} acceptedCiphertext,${CT_UINT256} counterpartCiphertext,${CT_UINT256} lpCiphertext)`,
  `function requestMyPosition(bytes32 requestId,uint64 deadline) returns (${CT_UINT256} sharesCiphertext,${CT_UINT256} amount0Ciphertext,${CT_UINT256} amount1Ciphertext,${CT_UINT256} priceX18Ciphertext)`,
  `function requestRemoveLiquidityQuote(${IT_UINT256} shares,bytes32 requestId,uint64 deadline) returns (${CT_UINT256} sharesCiphertext,${CT_UINT256} amount0Ciphertext,${CT_UINT256} amount1Ciphertext,${CT_UINT256} priceX18Ciphertext)`,
  `function requestLockedPosition(bytes32 lockId,bytes32 requestId,uint64 deadline) returns (${CT_UINT256} sharesCiphertext,${CT_UINT256} amount0Ciphertext,${CT_UINT256} amount1Ciphertext,${CT_UINT256} priceX18Ciphertext)`,
  `function swapExactInput(${IT_UINT256} amountIn,${IT_UINT256} minAmountOut,bool zeroForOne,uint64 deadline) returns (${CT_UINT256} amountOut)`,
  `function addLiquidity(${IT_UINT256} amount0Desired,${IT_UINT256} amount1Desired,${IT_UINT256} minShares,${IT_UINT256} minPriceX18,${IT_UINT256} maxPriceX18,bool expectedInitialized,uint64 deadline) returns (${CT_UINT256} mintedShares)`,
  `function removeLiquidity(${IT_UINT256} shares,${IT_UINT256} minAmount0,${IT_UINT256} minAmount1,uint64 deadline) returns (${CT_UINT256} amount0,${CT_UINT256} amount1)`,
  `function lockShares(${IT_UINT256} shares,uint64 unlockTime,bool permanent,uint64 deadline) returns (bytes32 lockId)`,
  "function unlockShares(bytes32 lockId)",
  "function collectProtocolFees(bool collectToken0,bool collectToken1)",
  "function lockInfo(bytes32 lockId) view returns (address owner,uint64 unlockTime,bool permanent,bool released)",
  "event LiquidityLocked(bytes32 indexed lockId,address indexed owner,uint64 unlockTime,bool permanent)",
  `event ConfidentialQuoteResult(address indexed caller,bytes32 indexed requestId,bool indexed zeroForOne,${CT_UINT256} result)`,
  `event ConfidentialLiquidityQuoteResult(address indexed caller,bytes32 indexed requestId,bool indexed token0Specified,${CT_UINT256} acceptedCiphertext,${CT_UINT256} counterpartCiphertext,${CT_UINT256} lpCiphertext)`,
  `event ConfidentialPositionResult(address indexed caller,bytes32 indexed requestId,${CT_UINT256} sharesCiphertext,${CT_UINT256} amount0Ciphertext,${CT_UINT256} amount1Ciphertext,${CT_UINT256} priceX18Ciphertext)`,
  `event ConfidentialRemoveLiquidityQuoteResult(address indexed caller,bytes32 indexed requestId,${CT_UINT256} sharesCiphertext,${CT_UINT256} amount0Ciphertext,${CT_UINT256} amount1Ciphertext,${CT_UINT256} priceX18Ciphertext)`,
  `event ConfidentialLockedPositionResult(address indexed caller,bytes32 indexed requestId,bytes32 indexed lockId,${CT_UINT256} sharesCiphertext,${CT_UINT256} amount0Ciphertext,${CT_UINT256} amount1Ciphertext,${CT_UINT256} priceX18Ciphertext)`,
  "event ConfidentialProtocolFeesCollected(address indexed token,address indexed feeVault,uint32 aggregatedSwapCount)",
] as const;
